###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine

    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=lingoda
        - MYSQL_USER=project
        - MYSQL_PASSWORD=project
      ports:
        - "8092:3306"
    mysql_test:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=lingoda_test
        - MYSQL_USER=project
        - MYSQL_PASSWORD=project
      ports:
        - "8093:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8090:80"

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

